spring.application.name=gio-kebab-backend
spring.profiles.default=local
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
restaurant.time-zone=${RESTAURANT_TIME_ZONE:Europe/Vilnius}
