CREATE TABLE menu_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL CHECK (TRIM(name) <> ''),
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE menu_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES menu_category(id) ON DELETE RESTRICT,
    name VARCHAR(160) NOT NULL CHECK (TRIM(name) <> ''),
    description VARCHAR(1000) NOT NULL CHECK (TRIM(description) <> ''),
    price_eur NUMERIC(10, 2) NOT NULL CHECK (price_eur > 0),
    active BOOLEAN NOT NULL,
    available BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX menu_item_category_id_idx ON menu_item(category_id);
