CREATE TABLE promotion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL CHECK (TRIM(title) <> ''),
    description VARCHAR(500) CHECK (description IS NULL OR TRIM(description) <> ''),
    active BOOLEAN NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE,
    ends_at TIMESTAMP WITH TIME ZONE,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT promotion_window CHECK (starts_at IS NULL OR ends_at IS NULL OR ends_at >= starts_at)
);

CREATE INDEX promotion_public_order_idx ON promotion(active, display_order, id);
