CREATE TABLE lunch_menu_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week VARCHAR(9) NOT NULL CHECK (day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    name VARCHAR(160) NOT NULL CHECK (TRIM(name) <> ''),
    description VARCHAR(1000) CHECK (description IS NULL OR TRIM(description) <> ''),
    price_eur NUMERIC(10, 2) NOT NULL CHECK (price_eur > 0),
    active BOOLEAN NOT NULL,
    available BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    image_url VARCHAR(2048),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX lunch_menu_item_day_order_idx ON lunch_menu_item(day_of_week, display_order, id);

CREATE TABLE lunch_menu_item_translation (
    item_id BIGINT NOT NULL REFERENCES lunch_menu_item(id) ON DELETE CASCADE,
    locale VARCHAR(2) NOT NULL CHECK (locale IN ('en', 'ru', 'ka')),
    name VARCHAR(160),
    description VARCHAR(1000),
    PRIMARY KEY (item_id, locale),
    CHECK (name IS NULL OR TRIM(name) <> ''),
    CHECK (description IS NULL OR TRIM(description) <> ''),
    CHECK (name IS NOT NULL OR description IS NOT NULL)
);
